import type { Metadata } from "next";
import localFont from "next/font/local";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import UserProvider from "@/context/userProvider";
import Navabar from "@/components/Navbar";
import { ReactQueryComponent } from "@/components/ReactQuery/ReactQueyComp";
import { Providers } from "@/components/NextUIProvider/Provider";
import Menubar from "@/components/Menubar";
import Footer from "@/components/Footer";

import { Arimo, Exo_2, Karla, Noto_Serif } from "next/font/google";

const poppins = Exo_2({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--var-poppins",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryComponent>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}>
          <Providers>
            <UserProvider>
              <Navabar />

              <Menubar />
              {children}
              <Footer />
            </UserProvider>
            <ToastContainer />
          </Providers>
        </body>
      </html>
    </ReactQueryComponent>
  );
}
